### PR TITLE
Julia v4 syntax fixes and added the ability to use a non-default audio device

### PR DESCRIPTION
**Pull request by wherrera10**
Two sets of changes:

1. Changes to several files to clean up syntax warnings with v4.0. This used the Compat module.

2. Added code to open non-default device for input or output streams. An example of such usage is placed in an added test file.

### CODE REVIEW

**Comment by ssfrr** [comment]
I fixed things up so that the tests run and pushed to the `wherrera10_test` branch, as well as fixing some more 0.4 incompatibilities and removing some extra `@compat`s. (You don't need `@compat` to use new type names as they're just typealiases in the Compat package).

Would you mind some usage examples to the README showing how to use the new functionality? I briefly looked through but it wasn't clear to me what was the public vs private interface for the new features.

If possible it would be great to see tests as well (now that the test suite passes! :smirk:), though I know that could be tough with the stuff that directly interfaces with the hardware.

**Comment by wherrera10** [comment]
I think that the public interface would be
Pa_OpenStream,
which returns a stream with public interface as a
Pa_AudioStream,

with the functions

read_Pa_AudioStream and
write_Pa_AudioStream

for blocking I/O and reads or writes, or direct use of the
Pa_audiostram.sbuffer as a read or write buffer in non-blocking code.

I'll try to push a test file and a modified README over to the test branch.

--Bill

**Comment by wherrera10** [comment]
I fixed some of the added code a bit and added a callback functionality as
well (part of the portaudio package).  The callback functionality involves
passing function pointers and buffers between C and julia and calling julia
from C, so that part (callbacks) needs testing and is still experimental.

**Comment by wherrera10** [comment]
Okay, the callback I/O is done, but is not as pretty because Julia cannot
send closure information in a C callback for some reason.

**Comment by wherrera10** [comment]
Added callbacks and cleaned up blocking I/O

**Pull request closed without merging**
